// 綜合 cron:①發送到期的排程貼文 ②若開啟「每日自動產文」且今日未產,依近期成效最佳主題產 1 篇並排入佇列
// 外部 cron 每小時打這裡(GET);前端也可 POST 手動觸發。
import { NextResponse } from 'next/server';
import {
  getThreadsCreds, publishThreads, appendPostLog, readPostLog,
  readQueue, writeQueue, readSettings, writeSettings, readTopics, readCanonicalProfile,
  readWeekly, maybeRefreshThreadsToken,
} from '@/lib/threads.js';
import { writePost } from '@/lib/post-writer.js';
import { makeWeatherPost } from '@/lib/weather.js';
import { medicalClinicProfile } from '@/lib/verticals.js';

// 區分變數交叉組合(與前端一致)
function activeDimsOf(topic) {
  if (topic?.activeDims?.length) return topic.activeDims;
  if (topic?.variables?.length) return [{ label: topic.varLabel || '對象', values: topic.variables }];
  return [];
}
function pickStride(total) {
  if (total <= 2) return 1;
  const gcd = (a, b) => (b ? gcd(b, a % b) : a);
  const base = Math.max(2, Math.round(total * 0.6180339887));
  for (let k = 0; k < total; k++) {
    const up = base + k; if (up < total && gcd(up, total) === 1) return up;
    const dn = base - k; if (dn > 1 && gcd(dn, total) === 1) return dn;
  }
  return 1;
}
function crossCombo(dims, idx) {
  if (!dims.length) return { label: '', value: '' };
  const total = dims.reduce((a, d) => a * Math.max(1, (d.values || []).length), 1);
  const stride = pickStride(total);
  let rem = ((((idx * stride) % total) + total) % total);
  const labels = [], values = [];
  for (const d of dims) { const len = Math.max(1, (d.values || []).length); const vi = rem % len; rem = Math.floor(rem / len); labels.push(d.label); values.push((d.values || [])[vi]); }
  return { label: labels.join('×'), value: values.filter(Boolean).join(' · ') };
}

// 依主題綁定的療程排出取用清單(★=3倍),再依 seed 取一個 + 組 context(與前端一致)
function weeklyTreatmentContext(topic, products, seed) {
  const names = topic?.treatments || []; const starred = topic?.starred || [];
  const prods = names.map((n) => products.find((p) => p.name === n)).filter((p) => p && p.include_in_image_gen !== false);
  if (!prods.length) return '';
  const list = []; for (const p of prods) { const w = starred.includes(p.name) ? 3 : 1; for (let k = 0; k < w; k++) list.push(p); }
  const p = list[seed % list.length]; if (!p) return '';
  const inj = topic.inject || {}; const parts = [];
  if (inj.name !== false) parts.push(`療程名稱:${p.name}`);
  if (inj.price !== false && p.promo_offer) parts.push(`價格優惠:${p.promo_offer}`);
  if (p.features) parts.push(`特點:${p.features}`);
  if (inj.imageFocus !== false && p.image_focus) parts.push(`強化圖片方向:${p.image_focus}`);
  return parts.join('\n');
}

export const runtime = 'nodejs';
export const maxDuration = 300;

const BASE = 'https://graph.threads.net/v1.0';
const MAX_POST_PER_RUN = 8;

async function insightsEngagement(mediaId, token) {
  try {
    const qs = new URLSearchParams({ metric: 'likes,replies,reposts,quotes', access_token: token }).toString();
    const r = await fetch(`${BASE}/${mediaId}/insights?${qs}`);
    const d = await r.json();
    let sum = 0; for (const m of (d.data || [])) sum += Number(m?.values?.[0]?.value ?? m?.total_value?.value ?? 0) || 0;
    return sum;
  } catch (_) { return 0; }
}

// 挑「效果最好的主題」:有 insights 用近30天互動最高的 topicName;否則挑最久沒用到的 enabled 主題
async function pickTopic(topics, token) {
  const enabled = topics.filter((t) => t.enabled !== false && t.name);
  if (enabled.length === 0) return null;
  const log = (await readPostLog()).filter((e) => (e.ts || 0) >= Date.now() - 30 * 86400000);
  if (token && log.length) {
    const recent = log.slice(0, 40);
    const byTopic = {};
    for (let i = 0; i < recent.length; i += 5) {
      const chunk = recent.slice(i, i + 5);
      const eng = await Promise.all(chunk.map((e) => e.mediaId ? insightsEngagement(e.mediaId, token) : Promise.resolve(0)));
      chunk.forEach((e, j) => { const k = e.topicName || ''; byTopic[k] = (byTopic[k] || 0) + eng[j]; });
    }
    const best = Object.entries(byTopic).sort((a, b) => b[1] - a[1])[0]?.[0];
    const match = enabled.find((t) => t.name === best);
    if (match) return match;
  }
  // fallback:挑最久沒在 log 出現過的(輪替求多元)
  const lastUsed = {};
  for (const e of (await readPostLog())) { const k = e.topicName; if (k && !(k in lastUsed)) lastUsed[k] = e.ts || 0; }
  return enabled.slice().sort((a, b) => (lastUsed[a.name] || 0) - (lastUsed[b.name] || 0))[0];
}

async function run() {
  const out = { posted: 0, failed: 0, remaining: 0, autoGenerated: false, autoTopic: '', tokenRefresh: null };

  // ⓪ token 自動續期(剩 <10 天就換新的,永不因過期而斷)
  try { out.tokenRefresh = await maybeRefreshThreadsToken(); } catch (e) { out.tokenRefresh = { refreshed: false, error: String(e.message).slice(0, 200) }; }

  const { token, ok } = await getThreadsCreds();
  if (!ok) return { ...out, error: 'Threads 未設定' };

  // ⓪-2 每週排程 → 今天的時段materialize成佇列(每天一次)。排程設在各「主題」上(topic.schedule)。
  try {
    const s2 = await readSettings();
    const today = new Date();
    const dateKey = `${today.getFullYear()}-${today.getMonth() + 1}-${today.getDate()}`;
    if (s2.lastWeeklyDate !== dateKey) {
      const dow = today.getDay();
      const topics = await readTopics();
      // 收集今天要發的 (topic, time)
      const due = [];
      for (const topic of topics) {
        if (topic.enabled === false) continue;
        for (const slot of (topic.schedule || [])) {
          if (slot.weekday === dow && /^\d{2}:\d{2}$/.test(slot.time || '')) due.push({ topic, time: slot.time });
        }
      }
      let made = 0;
      if (due.length) {
        const prof = { ...medicalClinicProfile(), ...(await readCanonicalProfile() || {}) };
        const products = prof.products || [];
        const items = await readQueue();
        let seed = 0;
        for (const { topic, time } of due) {
          const [hh, mm] = String(time).split(':').map(Number);
          const when = new Date(today); when.setHours(hh || 12, mm || 0, 0, 0);
          const tc = weeklyTreatmentContext(topic, products, dow + seed);
          const combo = crossCombo(activeDimsOf(topic), dow + seed);
          const text = await writePost({ type: topic.type, topicName: topic.name, prompt: topic.prompt, brand: prof.brand, brand_persona: prof.brand_persona, audience: prof.audience, clinic: prof.clinic, variant: dow + seed, treatmentContext: tc, culture: !!topic.culture, varLabel: combo.label, variableValue: combo.value });
          if (text) { items.push({ id: `wk-${dateKey}-${topic.id}-${time.replace(':', '')}`, text, topicId: topic.id, topicName: topic.name, type: topic.type, scheduledTs: when.getTime(), status: 'pending', mediaId: '', permalink: '', error: '', auto: true }); made++; }
          seed++;
        }
        if (made) await writeQueue(items);
      }
      await writeSettings({ ...s2, lastWeeklyDate: dateKey });
      out.weeklyMaterialized = made;
    }
  } catch (e) { out.weeklyError = String(e.message).slice(0, 200); }

  // ⓪-3 每日定時天氣提醒:到指定時間、當天未發 → 抓「當下天氣」產文並排入(當天發)
  try {
    const s3 = await readSettings();
    const wd = s3.weatherDaily;
    if (wd && wd.enabled && /^\d{2}:\d{2}$/.test(wd.time || '')) {
      const today = new Date();
      const dateKey = `${today.getFullYear()}-${today.getMonth() + 1}-${today.getDate()}`;
      const [hh, mm] = wd.time.split(':').map(Number);
      const dueMin = (hh || 0) * 60 + (mm || 0);
      const nowMin = today.getHours() * 60 + today.getMinutes();
      if (s3.lastWeatherDate !== dateKey && nowMin >= dueMin) {
        const prof = { ...medicalClinicProfile(), ...(await readCanonicalProfile() || {}) };
        const { text } = await makeWeatherPost({ brand: prof.brand, brand_persona: prof.brand_persona, audience: prof.audience, clinic: prof.clinic });
        if (text) {
          const items0 = await readQueue();
          items0.push({ id: `wx-${dateKey}`, text, topicId: '', topicName: '天氣提醒', type: 'text', scheduledTs: Date.now(), status: 'pending', mediaId: '', permalink: '', error: '', auto: true });
          await writeQueue(items0);
        }
        await writeSettings({ ...s3, lastWeatherDate: dateKey });
        out.weatherPosted = !!text;
      }
    }
  } catch (e) { out.weatherError = String(e.message).slice(0, 200); }

  // ① 發送到期
  let items = await readQueue();
  const now = Date.now();
  const due = items.filter((x) => x.status === 'pending' && (x.scheduledTs || 0) <= now).slice(0, MAX_POST_PER_RUN);
  for (const it of due) {
    try {
      const { mediaId, permalink } = await publishThreads(it.text, it.imageUrl || "");
      it.status = 'posted'; it.mediaId = mediaId; it.permalink = permalink; it.postedTs = Date.now();
      await appendPostLog({ ts: it.postedTs, mediaId, permalink, topicId: it.topicId, topicName: it.topicName, type: it.type, textPreview: (it.text || '').slice(0, 60) });
      out.posted++;
    } catch (e) { it.status = 'failed'; it.error = String(e.message).slice(0, 200); out.failed++; }
  }
  if (due.length) await writeQueue(items);

  // ② 每日自動產文
  const s = await readSettings();
  if (s.dailyAuto && (now - (s.lastAutoTs || 0)) >= 20 * 3600 * 1000) {
    try {
      const topics = await readTopics();
      const topic = await pickTopic(topics, token);
      if (topic) {
        const prof = { ...medicalClinicProfile(), ...(await readCanonicalProfile() || {}) };
        const combo = crossCombo(activeDimsOf(topic), Math.floor(now / 86400000));
        const text = await writePost({ type: topic.type, topicName: topic.name, prompt: topic.prompt, brand: prof.brand, brand_persona: prof.brand_persona, audience: prof.audience, clinic: prof.clinic, culture: !!topic.culture, varLabel: combo.label, variableValue: combo.value });
        if (text) {
          items = await readQueue();
          items.push({ id: `auto-${now}`, text, topicId: topic.id || '', topicName: topic.name, type: topic.type, scheduledTs: now, status: 'pending', mediaId: '', permalink: '', error: '', auto: true });
          await writeQueue(items);
          await writeSettings({ ...s, lastAutoTs: now });
          out.autoGenerated = true; out.autoTopic = topic.name;
        }
      }
    } catch (e) { out.autoError = String(e.message).slice(0, 200); }
  }

  out.remaining = (await readQueue()).filter((x) => x.status === 'pending').length;
  return out;
}

export async function GET(req) {
  const secret = process.env.CRON_SECRET;
  if (secret) {
    const auth = req.headers.get('authorization') || '';
    if (auth !== `Bearer ${secret}`) return NextResponse.json({ error: 'unauthorized' }, { status: 401 });
  }
  try { return NextResponse.json(await run()); } catch (e) { return NextResponse.json({ error: e.message }, { status: 500 }); }
}
export async function POST() {
  try { return NextResponse.json(await run()); } catch (e) { return NextResponse.json({ error: e.message }, { status: 500 }); }
}
