// 綜合 cron:①發送到期的排程貼文 ②若開啟「每日自動產文」且今日未產,依近期成效最佳主題產 1 篇並排入佇列
// 外部 cron 每小時打這裡(GET);前端也可 POST 手動觸發。
import { NextResponse } from 'next/server';
import {
  getThreadsCreds, publishThreadsText, appendPostLog, readPostLog,
  readQueue, writeQueue, readSettings, writeSettings, readTopics, readCanonicalProfile,
  maybeRefreshThreadsToken,
} from '@/lib/threads.js';
import { writePost } from '@/lib/post-writer.js';
import { medicalClinicProfile } from '@/lib/verticals.js';

export const runtime = 'nodejs';
export const maxDuration = 300;

const BASE = 'https://graph.threads.net/v1.0';
const MAX_POST_PER_RUN = 8;

async function insightsEngagement(mediaId, token) {
  try {
    const qs = new URLSearchParams({ metric: 'likes,replies,reposts,quotes', access_token: token }).toString();
    const r = await fetch(`${BASE}/${mediaId}/insights?${qs}`);
    const d = await r.json();
    let sum = 0; for (const m of (d.data || [])) sum += Number(m?.values?.[0]?.value ?? m?.total_value?.value ?? 0) || 0;
    return sum;
  } catch (_) { return 0; }
}

// 挑「效果最好的主題」:有 insights 用近30天互動最高的 topicName;否則挑最久沒用到的 enabled 主題
async function pickTopic(topics, token) {
  const enabled = topics.filter((t) => t.enabled !== false && t.name);
  if (enabled.length === 0) return null;
  const log = (await readPostLog()).filter((e) => (e.ts || 0) >= Date.now() - 30 * 86400000);
  if (token && log.length) {
    const recent = log.slice(0, 40);
    const byTopic = {};
    for (let i = 0; i < recent.length; i += 5) {
      const chunk = recent.slice(i, i + 5);
      const eng = await Promise.all(chunk.map((e) => e.mediaId ? insightsEngagement(e.mediaId, token) : Promise.resolve(0)));
      chunk.forEach((e, j) => { const k = e.topicName || ''; byTopic[k] = (byTopic[k] || 0) + eng[j]; });
    }
    const best = Object.entries(byTopic).sort((a, b) => b[1] - a[1])[0]?.[0];
    const match = enabled.find((t) => t.name === best);
    if (match) return match;
  }
  // fallback:挑最久沒在 log 出現過的(輪替求多元)
  const lastUsed = {};
  for (const e of (await readPostLog())) { const k = e.topicName; if (k && !(k in lastUsed)) lastUsed[k] = e.ts || 0; }
  return enabled.slice().sort((a, b) => (lastUsed[a.name] || 0) - (lastUsed[b.name] || 0))[0];
}

async function run() {
  const out = { posted: 0, failed: 0, remaining: 0, autoGenerated: false, autoTopic: '', tokenRefresh: null };

  // ⓪ token 自動續期(剩 <10 天就換新的,永不因過期而斷)
  try { out.tokenRefresh = await maybeRefreshThreadsToken(); } catch (e) { out.tokenRefresh = { refreshed: false, error: String(e.message).slice(0, 200) }; }

  const { token, ok } = await getThreadsCreds();
  if (!ok) return { ...out, error: 'Threads 未設定' };

  // ① 發送到期
  let items = await readQueue();
  const now = Date.now();
  const due = items.filter((x) => x.status === 'pending' && (x.scheduledTs || 0) <= now).slice(0, MAX_POST_PER_RUN);
  for (const it of due) {
    try {
      const { mediaId, permalink } = await publishThreadsText(it.text);
      it.status = 'posted'; it.mediaId = mediaId; it.permalink = permalink; it.postedTs = Date.now();
      await appendPostLog({ ts: it.postedTs, mediaId, permalink, topicId: it.topicId, topicName: it.topicName, type: it.type, textPreview: (it.text || '').slice(0, 60) });
      out.posted++;
    } catch (e) { it.status = 'failed'; it.error = String(e.message).slice(0, 200); out.failed++; }
  }
  if (due.length) await writeQueue(items);

  // ② 每日自動產文
  const s = await readSettings();
  if (s.dailyAuto && (now - (s.lastAutoTs || 0)) >= 20 * 3600 * 1000) {
    try {
      const topics = await readTopics();
      const topic = await pickTopic(topics, token);
      if (topic) {
        const prof = { ...medicalClinicProfile(), ...(await readCanonicalProfile() || {}) };
        const text = await writePost({ type: topic.type, topicName: topic.name, prompt: topic.prompt, brand: prof.brand, brand_persona: prof.brand_persona, audience: prof.audience, clinic: prof.clinic });
        if (text) {
          items = await readQueue();
          items.push({ id: `auto-${now}`, text, topicId: topic.id || '', topicName: topic.name, type: topic.type, scheduledTs: now, status: 'pending', mediaId: '', permalink: '', error: '', auto: true });
          await writeQueue(items);
          await writeSettings({ ...s, lastAutoTs: now });
          out.autoGenerated = true; out.autoTopic = topic.name;
        }
      }
    } catch (e) { out.autoError = String(e.message).slice(0, 200); }
  }

  out.remaining = (await readQueue()).filter((x) => x.status === 'pending').length;
  return out;
}

export async function GET(req) {
  const secret = process.env.CRON_SECRET;
  if (secret) {
    const auth = req.headers.get('authorization') || '';
    if (auth !== `Bearer ${secret}`) return NextResponse.json({ error: 'unauthorized' }, { status: 401 });
  }
  try { return NextResponse.json(await run()); } catch (e) { return NextResponse.json({ error: e.message }, { status: 500 }); }
}
export async function POST() {
  try { return NextResponse.json(await run()); } catch (e) { return NextResponse.json({ error: e.message }, { status: 500 }); }
}
